"""Add On-Demand Model Config table

Revision ID: 232402d894ee
Revises: a8d0956c543f
Create Date: 2025-12-10 12:50:13.827211

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "232402d894ee"
down_revision: str | Sequence[str] | None = "a8d0956c543f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ondemandmodelconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tracking_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("idle_ttl", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deploy_spec_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_on_demand_unique_enabled",
        "ondemandmodelconfig",
        ["model_name"],
        unique=True,
        postgresql_where=sa.text("enabled = true"),
        sqlite_where=sa.text("enabled = 1"),
    )
    op.create_index(
        op.f("ix_ondemandmodelconfig_model_name"),
        "ondemandmodelconfig",
        ["model_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ondemandmodelconfig_model_name"), table_name="ondemandmodelconfig")
    op.drop_index(
        "ix_on_demand_unique_enabled",
        table_name="ondemandmodelconfig",
        postgresql_where=sa.text("enabled = true"),
        sqlite_where=sa.text("enabled = 1"),
    )
    op.drop_table("ondemandmodelconfig")
    # ### end Alembic commands ###
