"""Add model server table for lifecycle and usage management

Revision ID: a8d0956c543f
Revises: 1859866dbf86
Create Date: 2025-11-18 17:07:06.957505

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8d0956c543f"
down_revision: str | Sequence[str] | None = "1859866dbf86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model",
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "deployment_type",
            sa.Enum("AUTO", "MANUAL", "STATIC", name="modeldeploymenttype"),
            nullable=False,
        ),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("idle_ttl", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("model_name"),
    )
    op.create_index("ix_model_usage_deployment_type", "model", ["deployment_type"], unique=False)
    op.create_index("ix_model_usage_last_used_at", "model", ["last_used_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_usage_last_used_at", table_name="model")
    op.drop_index("ix_model_usage_deployment_type", table_name="model")
    op.drop_table("model")
    # ### end Alembic commands ###
