{
 "title": "Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processed Model Tasks",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model, task) (gateway_tasks_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, endpoint) (gateway_requests_total{endpoint!=\"/metrics\", endpoint!=\"/metrics/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed Models",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model, model_uri) (gateway_models_deployed_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}