{
 "title": "Scheduler",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (scheduler_tasks_completed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scheduler_tasks_scheduled_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requeued Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scheduler_tasks_requeued_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}